# SKILL-010: Environment-Specific Bash Mastery
# Detects hardware/OS context and generates optimization profiles

param(
    [string]$OutputDir = ".env"
)

$ErrorActionPreference = "Stop"
$outputPath = Join-Path (Get-Location) $OutputDir
if (-not (Test-Path $outputPath)) { New-Item -ItemType Directory -Path $outputPath -Force | Out-Null }

Write-Host "Profiling System Hardware..." -ForegroundColor Cyan

# CPU Info
$cpu = Get-CimInstance Win32_Processor
$logicalCores = $cpu.NumberOfLogicalProcessors
$nodes = $cpu.Name

# Memory Info
$os = Get-CimInstance Win32_OperatingSystem
$totalRamBytes = $os.TotalVisibleMemorySize * 1024
$totalRamGB = [math]::Round($totalRamBytes / 1GB, 2)
$freeRamGB = [math]::Round(($os.FreePhysicalMemory * 1024) / 1GB, 2)

# GPU Check (Simple presence of nvidia-smi)
$hasCuda = $false
try {
    if (Get-Command nvidia-smi -ErrorAction SilentlyContinue) {
        $hasCuda = $true
    }
}
catch {}

# Profile Object
$profile = @{
    generated_at = Get-Date
    os           = $os.Caption
    cpu          = @{
        name               = $nodes
        cores              = $cpu.NumberOfCores
        logical_processors = $logicalCores
    }
    memory       = @{
        total_gb = $totalRamGB
        free_gb  = $freeRamGB
    }
    capabilities = @{
        has_cuda           = $hasCuda
        powershell_version = $PSVersionTable.PSVersion.ToString()
    }
}

# Save JSON
$jsonPath = Join-Path $outputPath "SYSTEM_PROFILE.json"
$profile | ConvertTo-Json -Depth 5 | Out-File -FilePath $jsonPath

# Generate Optimization Flags (.env)
$envContent = "# Optimization Flags for this Environment`n"
$envContent += "# Generated by SKILL-010 on $(Get-Date)`n`n"

# CPU Optimizations
$envContent += "export MAKEFLAGS=`"-j$logicalCores`"`n"
$envContent += "export OMP_NUM_THREADS=$logicalCores`n"
$envContent += "export UV_THREADPOOL_SIZE=$logicalCores`n"

# Node.js Memory (Use ~80% of total RAM)
$nodeMem = [math]::Floor($totalRamBytes / 1MB * 0.8)
$envContent += "export NODE_OPTIONS=`"--max-old-space-size=$nodeMem`"`n"

# CUDA
if ($hasCuda) {
    $envContent += "export CUDA_VISIBLE_DEVICES=0`n" # Default to first GPU
}

$envPath = Join-Path $outputPath "OPTIMIZED_FLAGS.env"
$envContent | Out-File -FilePath $envPath -Encoding utf8

Write-Host "✅ System Profile Generated!" -ForegroundColor Green
Write-Host "   JSON: $jsonPath" -ForegroundColor Cyan
Write-Host "   ENV:  $envPath" -ForegroundColor Cyan
Write-Host ""
Write-Host "   Specs Detected:"
Write-Host "   - CPU: $nodes ($logicalCores threads)"
Write-Host "   - RAM: $totalRamGB GB"
Write-Host "   - GPU: $(if ($hasCuda) { 'NVIDIA Detected' } else { 'None/Unknown' })"
